version: "3.8"

services:
  t-mysqldb:
    container_name: t-mysqldb
    image: mysql
    environment:
#      MYSQL_USER: root
#      MYSQL_PASSWORD: Bikar0001@
      MYSQL_DATABASE: onlineshop
      MYSQL_ROOT_PASSWORD: Bikar0001@
    ports:
      - 3303:3306
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      ecommerce-backend:

  ecommerce:
    container_name: t-ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 19090:9090
    depends_on:
      - t-mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://t-mysqldb:3306/onlineshop
      - spring.datasource.username=root
      - spring.datasource.password=Bikar0001@
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      ecommerce-backend:
    restart: on-failure




networks:
  ecommerce-backend:

