version: "3.8"

services:
  t-mysqldb:
    container_name: t-mysqldb
    image: mysql
    environment:
#      MYSQL_USER: root
#      MYSQL_PASSWORD: Bikar0001@
      MYSQL_DATABASE: onlineshop
      MYSQL_ROOT_PASSWORD: Bikar0001@
    ports:
      - 3303:3306
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      ecommerce-backend:

  ecommerce:
    container_name: t-ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 19090:9090
    depends_on:
      - t-mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://t-mysqldb:3306/onlineshop
      - spring.datasource.username=root
      - spring.datasource.password=Bikar0001@
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      ecommerce-backend:
    restart: on-failure

  ecommerce-python:
    container_name: t-ecommerce-python
    image: python:3.12
    volumes:
      - ./python-sources:/pythonFolder
    working_dir: /pythonFolder
    command: ["python", "hello.py"]
    networks:
      - ecommerce-backend

  ecommerce-prometheus:
    container_name: t-ecommerce-prometheus
    image: prom/prometheus:v2.35.0
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    network_mode: host
    ports:
      - 9090:9090

  ecommerce-grafana:
    container_name: t-ecommerce-grafana
    image: grafana/grafana-oss:8.5.
    pull_policy: always
    network_mode: host
    restart: unless-stopped
    user: root
#    ports:
#      - 3000:3000
    links:
      - ecommerce-prometheus:ecommerce-prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      # Enable for logging
      - GF_LOG_MODE=console file
      #- GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug


networks:
  ecommerce-backend:

